apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-app
  template:
    metadata:
      labels:
        app: core-app
    spec:
      containers:
        - name: core-app
          image: disertation.azurecr.io/core-app:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: API_URL
              value: https://www.rares-disertation.xyz/content-management-service/api
            - name: AUTH0_DOMAIN
              value: dev-re5ucc1nn12lb5qo.us.auth0.com
            - name: AUTH0_CLIENTID
              value: 7PsLF1tiowoy50Ru4EW4EiWwk3uG6ylE
            - name: AUTH0_AUDIENCE
              value: https://hello-world.example.com
            - name: AUTH0_REDIRECT_URI
              value: https://www.rares-disertation.xyz/callback
---
apiVersion: v1
kind: Service
metadata:
  name: core-app
  labels:
    app: core-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: core-app
