apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: header-app
  template:
    metadata:
      labels:
        app: header-app
    spec:
      containers:
        - name: header-app
          image: disertation.azurecr.io/header-app:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: CORE_APP
              value: https://www.rares-disertation.xyz/core-app
---
apiVersion: v1
kind: Service
metadata:
  name: header-app
  labels:
    app: header-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: header-app